language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
- osx
deploy:
  api_key:
    secure: jgRIkQ9dR7llqMyH/PrNL5DXrsBWy5b4E5hTdvEMFQYEWSBzi1sUoYrM86Yf4OZJoYMGtuTcXeJe+4Dk9DlgiI/RloQQJE6TuL25c4uLuvP0n1Vms5k9+sQCHTyGlUjZw9KPczMylmjoqZZd7t+XsGvGIs5KuarvH60TnxC+CDacM4Ya44kB+loMt94fRrHC9BsQEKo/hFDW3LY8ZtRb2YPCgzfvGaKetWpm0xJfvmWdANrzFWFb+eTbMGUjU6ifEhUeHroZiw05AyVSOSur2aw+RXoPmN+rIdA8szeQkNDFtwKA+O8uHMFK7CC7nVWPS5jWiBHjZJk3UFFTlfGUsFDzxDd0om2MJnYgNcaue7xDG0LcdQdDdl+XkJXEOMX4o1wlLtlRBFA18Me7sFqfG1Ti406HuSzabwzxjshfJdooprZpq/E+9Qg4cVzlc7G0r6qiudZtNgqz5LHXYnaN6zmSs5a8nRzPfgWUr3dZTCdXuz5AcsCD03eC69V9049KGvlz5vpo6OtQWd0Mxy/DE+Xet+xCmVorsJYhnTcgVxRM0LZdTgfJjzNhTWBZjT7W/d/4pYVyZlqbz5qT/gHipOHwM/BitS/7omIJh/+nOL8Nh12W9ujaW1rKye8b1hvvh1tLxEF2vyt356uxxa94FyuvH9SF8/25dwl8Acp8Cls=
  provider: cargo
  on:
    tags: true
